In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
from sklearn.model_selection import train_test_split


df=pd.read_csv("dataset.csv")
df.head()


ID       SITENAME     Mg   PH  K(Potassium)  NITRATE  SULPHATE  \
0   1   Vengalapuram  268.0  7.3          10.0    276.0     304.0   
1   2        Kavalur   94.9  7.2           3.0      2.0      12.0   
2   3      Alangayam  226.1  7.5           0.0     16.0     150.0   
3   4   Vaniyambadi1  211.6  7.3           5.0    140.0     264.0   
4   5  Sangilikuppam  238.3  7.2           2.0    174.0     240.0   

   EC(Electrical Conductivity)  Ca(Calcium)  Na(Sodium)  CARBONATE  \
0                         5730         16.0         850          0   
1                         1069         24.0          77          0   
2                         2830         20.0         300          0   
3                         3600         20.0         500          0   
4                         2300         24.0         152          0   

   BICARBONATE  CHLORIDE  FLUORIDE  SAR(Sodium Absorption Ratio)  \
0        878.0    1304.0       1.6                          10.9   
1        421.0     163.0       1.3                           1.6   
2        549.0     631.0       1.0                           4.2   
3        726.0     680.0       1.7                           7.2   
4        537.0     305.0       1.2                           2.1   

   RSC(Residual Sodium Carbonate waterQuality  
0                           -8.5            E  
1                           -2.1            A  
2                          -10.6            E  
3                           -6.5            E  
4                          -12.0            E

In [2]:
inputs = df.iloc[:, [ 2, 3,4,5,6,7,8,9,10,11,12,13,14,15]].values
target = df.iloc[:, -1].values

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
target=le.fit_transform(df['waterQuality'])
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [3]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion="entropy", max_depth=3)
classifier.fit(X_train, y_train.ravel())
y_pred = classifier.predict(X_test)


In [4]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[8 1 2 0 0]
 [0 0 0 0 0]
 [0 0 4 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
              precision    recall  f1-score   support

           0       1.00      0.73      0.84        11
           1       0.00      0.00      0.00         0
           2       0.67      0.80      0.73         5
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         1

    accuracy                           0.78        18
   macro avg       0.63      0.71      0.65        18
weighted avg       0.88      0.78      0.81        18



/Users/ankitraj/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ankitraj/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ankitraj/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
