In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
from sklearn.model_selection import train_test_split
import warnings

df=pd.read_csv("dataset.csv")
df.head()


ID       SITENAME     Mg   PH  K(Potassium)  NITRATE  SULPHATE  \
0   1   Vengalapuram  268.0  7.3          10.0    276.0     304.0   
1   2        Kavalur   94.9  7.2           3.0      2.0      12.0   
2   3      Alangayam  226.1  7.5           0.0     16.0     150.0   
3   4   Vaniyambadi1  211.6  7.3           5.0    140.0     264.0   
4   5  Sangilikuppam  238.3  7.2           2.0    174.0     240.0   

   EC(Electrical Conductivity)  Ca(Calcium)  Na(Sodium)  CARBONATE  \
0                         5730         16.0         850          0   
1                         1069         24.0          77          0   
2                         2830         20.0         300          0   
3                         3600         20.0         500          0   
4                         2300         24.0         152          0   

   BICARBONATE  CHLORIDE  FLUORIDE  SAR(Sodium Absorption Ratio)  \
0        878.0    1304.0       1.6                          10.9   
1        421.0     163.0       1.3                           1.6   
2        549.0     631.0       1.0                           4.2   
3        726.0     680.0       1.7                           7.2   
4        537.0     305.0       1.2                           2.1   

   RSC(Residual Sodium Carbonate waterQuality  
0                           -8.5            E  
1                           -2.1            A  
2                          -10.6            E  
3                           -6.5            E  
4                          -12.0            E

In [2]:
#dataset description
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   ID                             88 non-null     int64  
 1   SITENAME                       88 non-null     object 
 2   Mg                             88 non-null     float64
 3   PH                             88 non-null     float64
 4   K(Potassium)                   88 non-null     float64
 5   NITRATE                        88 non-null     float64
 6   SULPHATE                       88 non-null     float64
 7   EC(Electrical Conductivity)    88 non-null     int64  
 8   Ca(Calcium)                    88 non-null     float64
 9   Na(Sodium)                     88 non-null     int64  
 10  CARBONATE                      88 non-null     int64  
 11  BICARBONATE                    88 non-null     float64
 12  CHLORIDE                       88 non-null     float

In [3]:
df['waterQuality'] = df['waterQuality'].replace(['A'],'1')
df['waterQuality'] = df['waterQuality'].replace(['B'],'2')
df['waterQuality'] = df['waterQuality'].replace(['C'],'3')
df['waterQuality'] = df['waterQuality'].replace(['D'],'4')
df['waterQuality'] = df['waterQuality'].replace(['E'],'5')
df.head()

ID       SITENAME     Mg   PH  K(Potassium)  NITRATE  SULPHATE  \
0   1   Vengalapuram  268.0  7.3          10.0    276.0     304.0   
1   2        Kavalur   94.9  7.2           3.0      2.0      12.0   
2   3      Alangayam  226.1  7.5           0.0     16.0     150.0   
3   4   Vaniyambadi1  211.6  7.3           5.0    140.0     264.0   
4   5  Sangilikuppam  238.3  7.2           2.0    174.0     240.0   

   EC(Electrical Conductivity)  Ca(Calcium)  Na(Sodium)  CARBONATE  \
0                         5730         16.0         850          0   
1                         1069         24.0          77          0   
2                         2830         20.0         300          0   
3                         3600         20.0         500          0   
4                         2300         24.0         152          0   

   BICARBONATE  CHLORIDE  FLUORIDE  SAR(Sodium Absorption Ratio)  \
0        878.0    1304.0       1.6                          10.9   
1        421.0     163.0       1.3                           1.6   
2        549.0     631.0       1.0                           4.2   
3        726.0     680.0       1.7                           7.2   
4        537.0     305.0       1.2                           2.1   

   RSC(Residual Sodium Carbonate waterQuality  
0                           -8.5            5  
1                           -2.1            1  
2                          -10.6            5  
3                           -6.5            5  
4                          -12.0            5

In [4]:
y = df['waterQuality'].astype('int32')
x = df.drop(columns = ['SITENAME','ID','CARBONATE'], axis = 1)
model = x
model.head()

Mg   PH  K(Potassium)  NITRATE  SULPHATE  EC(Electrical Conductivity)  \
0  268.0  7.3          10.0    276.0     304.0                         5730   
1   94.9  7.2           3.0      2.0      12.0                         1069   
2  226.1  7.5           0.0     16.0     150.0                         2830   
3  211.6  7.3           5.0    140.0     264.0                         3600   
4  238.3  7.2           2.0    174.0     240.0                         2300   

   Ca(Calcium)  Na(Sodium)  BICARBONATE  CHLORIDE  FLUORIDE  \
0         16.0         850        878.0    1304.0       1.6   
1         24.0          77        421.0     163.0       1.3   
2         20.0         300        549.0     631.0       1.0   
3         20.0         500        726.0     680.0       1.7   
4         24.0         152        537.0     305.0       1.2   

   SAR(Sodium Absorption Ratio)  RSC(Residual Sodium Carbonate waterQuality  
0                          10.9                           -8.5            5  
1                           1.6                           -2.1            1  
2                           4.2                          -10.6            5  
3                           7.2                           -6.5            5  
4                           2.1                          -12.0            5

In [5]:
inputs = model.drop(columns = ['waterQuality'], axis = 1)
target = model['waterQuality'].astype('int32')

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
target=le.fit_transform(model['waterQuality'])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2, random_state = 35)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train.ravel())
y_pred = classifier.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Percentage Accuracy: ", accuracy_score(y_test, y_pred) * 100)

warnings.filterwarnings('ignore')
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy:  0.7777777777777778
Percentage Accuracy:  77.77777777777779
[[9 0 1 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 4]]
              precision    recall  f1-score   support

           0       1.00      0.90      0.95        10
           1       0.00      0.00      0.00         1
           2       0.33      0.50      0.40         2
           3       0.00      0.00      0.00         1
           4       0.80      1.00      0.89         4

    accuracy                           0.78        18
   macro avg       0.43      0.48      0.45        18
weighted avg       0.77      0.78      0.77        18

